django_basic/geekshop/adminapp/urls.py
from django.urls import include, path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.home, name='home'),

    path('users/create/', adminapp.ShopUserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.ShopUserList.as_view(), name='users'),
    path("users/update/<int:pk>/", adminapp.ShopUserUpdateView.as_view(), name="user_update"),
    path("users/delete/<int:pk>/", adminapp.ShopUserDeleteView.as_view(), name="user_delete"),

    path('categories/create/', adminapp.GoodsCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.GoodsCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/',
         adminapp.GoodsCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/',
         adminapp.GoodsCategoryDeleteView.as_view(), name='category_delete'),

    path('goods/create/', adminapp.GoodCreateView.as_view(), name='good_create'),
    path('goods/read/category/<int:pk>/', adminapp.goods, name='goods'),
    path('goods/read/<int:pk>/', adminapp.GoodDetailView.as_view(), name='good_read'),
    path('goods/update/<int:pk>/', adminapp.GoodUpdateView.as_view(), name='good_update'),
    path('goods/delete/<int:pk>/', adminapp.GoodDeleteView.as_view(), name='good_delete'),
]

django_basic/geekshop/authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'), 
    path('logout/', authapp.logout, name='logout'), 
    path('user/<slug:username>', authapp.userinfo, name='userinfo'), 
    path('user/register/', authapp.reg, name='reg'), 
    path('user/edit/<slug:username>', authapp.useredit, name='useredit'), 
#    path('user/')
]

django_basic/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')), 
    path('admin/', include('adminapp.urls', namespace='admin')),
]

django_basic/geekshop/adminapp/models.py
from django.db import models

# Create your models here.

django_basic/geekshop/adminapp/forms.py
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

django_basic/geekshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from setuptools.command.setopt import edit_config

from adminapp.forms import ShopUserAdminEditForm
from authapp.forms import ShopUserCreationForm
from authapp.models import ShopUser
from mainapp.models import Good, GoodsCategory


@user_passes_test(lambda u: u.is_superuser)
def home(req):
    return render(req, 'adminapp/home.html', dict())


# ====================== USERS ======================


class ShopUserCreateView(CreateView):
    model = ShopUser
    template_name = "adminapp/user_update.html"
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ShopUserList(ListView):
    model = ShopUser
    context_object_name = ''
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ShopUserUpdateView(UpdateView):
    model = ShopUser
    template_name = "adminapp/user_update.html"
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ShopUserDeleteView(DeleteView):
    model = ShopUser
    template_name = "adminapp/user_delete.html"
    success_url = reverse_lazy('adminapp:users')

    def delete(self, req, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# ====================== CATEGORIES ======================


class GoodsCategoryListView(ListView):
    model = GoodsCategory
    template_name = "adminapp/categories.html"

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GoodsCategoryCreateView(CreateView):
    model = GoodsCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy('adminapp:categories')
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GoodsCategoryUpdateView(UpdateView):
    model = GoodsCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy('adminapp:categories')
    fields = '__all__'

    def get_cotext_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / редактирование'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GoodsCategoryDeleteView(DeleteView):
    model = GoodsCategory
    template_name = "adminapp/category_delete.html"
    success_url = reverse_lazy('adminapp:categories')

    def delete(self, req, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# ====================== GOODS ======================


@user_passes_test(lambda u: u.is_superuser)
def goods(req, pk):
    category = get_object_or_404(GoodsCategory, pk=pk)
    goods_list = Good.objects.filter(category__pk=pk).order_by('caption')
    return render(req, 'adminapp/goods.html', {
        'category': category,
        'goods': goods_list,
    })


class GoodCreateView(CreateView):
    model = Good
    template_name = "adminapp/good_create.html"
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GoodDetailView(DetailView):
    model = Good
    template_name = "adminapp/good_read.html"

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GoodUpdateView(UpdateView):
    model = Good
    template_name = "adminapp/good_create.html"
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GoodDeleteView(DeleteView):
    model = Good
    template_name = "adminapp/good_delete.html"
    success_url = reverse_lazy('adminapp:goods', kwargs={'pk': 1})

    def delete(self, req, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

django_basic/geekshop/adminapp/templates/adminapp/admin_submenu.html
{% if user.is_authenticated %}
<div class="menuitem">
    <a href="{% url 'adminapp:users' %}">Пользователи</a>
</div>
<div class="menuitem">
    <a href="{% url 'adminapp:categories' %}">Категории</a>
</div>
<div class="menuitem">
    <a href="{% url 'adminapp:goods' 1 %}">Товары</a>
</div>
{% endif %}

django_basic/geekshop/adminapp/templates/adminapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}Администрирование</title>
    <link rel="stylesheet" href="https://unpkg.com/picnic">
    <link rel="stylesheet" href="{% static 'css/admin_style.css' %}">
</head>

<body>
    <div style="overflow: hidden;height: 55px;">

        <nav>
            <a href="{% url 'adminapp:home' %}" class="brand">
                <img class="logo" src="{% static 'img/logo_h75px.png' %}" />
                <span>Администрирование</span>
            </a>

            <!-- responsive-->
            <input id="bmenub" type="checkbox" class="show">
            <label for="bmenub" class="burger pseudo button">menu</label>

            <div class="menu">
                {% if user.is_authenticated %}
                <span class="username">{{user.username}}</span>
                <a href="{% url 'authapp:logout' %}" class="pseudo button">выйти</a>
                {% else %}
                <a href="{% url 'authapp:login' %}" class="pseudo button">войти</a>
                {% endif %}
            </div>
        </nav>

    </div>

    <div class="flex six">
        <div class="submenu">{% include "adminapp/admin_submenu.html" %}</div>
        <div class="content half two-fifth">

            {% block content %}

            {% endblock content %}

        </div>
    </div>
</body>

</html>

django_basic/geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<a class="button" href="{% url 'adminapp:category_create' %}">Новая категория</a>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>Название</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>

        {% for ob in object_list %}
        <tr>
            <td>{{ ob.pk }}</td>
            <td><a href="{% url 'adminapp:category_update' ob.pk %}">{{ ob.caption }}</a></td>
            <td>
                <a href="{% url 'adminapp:goods' ob.pk %}" class="button">Товары</a>
                <a class="button" href="{% url 'adminapp:category_delete' ob.pk %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить категорию "{{object.caption}}"?</p>
    <input type="submit" value="Удалить" class="button">
</form>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/good_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {{form.as_p}}
    <input type="submit" value="Сохранить"> <a href="{% url 'adminapp:goods' 1 %}" class="button">Все товары</a>
</form>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/good_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form action="" method="post">
{% csrf_token %}
<p>Вы уверены, что хотите удалить объект "{{object.caption}}" из категории "{{object.category.caption}}"?</p>
<input class="button" type="submit" value="Удалить">
</form>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/good_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<h3>{{object.caption}}</h3>
<p><img src="{% static object.get_image_path %}" alt=""></p>
<p><strong>{{object.category.caption}}</strong></p>
<p>{{object.brief_description}}</p>
<p>{{object.full_description}}</p>
<p>{{object.str_price}}</p>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/goods.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<a href="{% url 'adminapp:good_create' %}" class="button">Новый товар</a>
<table>
    <thead>
        <tr>
            <th>Изображение</th>
            <th>Название</th>
            <th>Цена</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for g in goods %}
        <tr>
            <td><img src="{{ g.get_image_path|media_folder_goods }}" alt="" class="good_img"></td>
            <td><a href="{% url 'adminapp:good_update' g.pk %}">{{g.caption}}</a></td>
            <td>{{g.str_price}}</td>
            <td>
            <a href="{% url 'adminapp:good_read' g.pk %}" class="button">Просмотр</a>
            <a href="{% url 'adminapp:good_update' g.pk %}" class="button">Редактировать</a>
            <a href="{% url 'adminapp:good_delete' g.pk %}" class="button">Удалить</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/home.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <p>Домашняя страница</p>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        <p>Уверены, что хотите удалить {{user_to_delete.username}}</p>
        
        {% if user_to_delete.first_name %}
            ({{user_to_delete.first_name|title}}
            
            {% if user_to_delete.last_name %}
                {{user_to_delete.last_name|title}}
            {% endif %})
                
        {% endif %}
        ?
        <form action="{% url 'adminapp:user_delete' user_to_delete.pk %}" method="POST">
            {% csrf_token %}
            <input class="button" type="submit" value="Удалить">
        </form>
        <a href="{% url 'adminapp:users' %}" class="button">Отмена</a>
    </div>
{% endblock content %}
    

django_basic/geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Сохранить">
    <a href="{% url 'adminapp:users' %}" class="button">К списку пользователей</a>
    </form>
{% endblock content %}

django_basic/geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<table>
    <a href="{% url 'adminapp:user_create' %}" class="button">Новый пользователь</a>
    <thead>
        <tr>
            <th>Аватар</th>
            <th>Логин</th>
            <th>Имя</th>
            <th>Возраст</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for ob in object_list %}
        <tr>
            <td>{{ ob.avatar.image_url|media_folder_users }}</td>
            <td><a href="{% url 'adminapp:user_update' ob.pk %}">{{ ob.username }}</a></td>
            <td>{{ ob.get_full_name }}</td>
            <td>{{ ob.age }}</td>
            <td><a class="button" href="{% url 'adminapp:user_delete' ob.pk %}">Удалить</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}