django_basic/geekshop/authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'), 
    path('logout/', authapp.logout, name='logout'), 
    path('user/<slug:username>', authapp.userinfo, name='userinfo'), 
    path('user/register/', authapp.reg, name='reg'), 
    path('user/edit/<slug:username>', authapp.useredit, name='useredit'), 
#    path('user/')
]

django_basic/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')), 
    path('admin/', include('adminapp.urls', namespace='admin')),
]

django_basic/geekshop/mainapp/urls.py
from django.urls import path
from .views import catalog, item, category

app_name = 'mainapp'

urlpatterns = [
    path('', catalog, name="index"), 
    path('category/<int:category_id>', category, name="category"), 
    path('item/<int:item_id>', item, name="item"), 
]

django_basic/geekshop/mainapp/models.py
from django.db import models


class GoodCharTemple(models.Model):

    class Meta:
        verbose_name = 'образец характеристики товара'
        verbose_name_plural = 'образцы характеристик товара'

    caption = models.CharField(verbose_name='название', max_length=255)
    category = models.ForeignKey(
        'GoodsCategory', models.CASCADE, verbose_name='категория')
    
    def __str__(self):
        return f'"{self.caption}" для "{self.category.caption}"'


class GoodsCategory(models.Model):

    class Meta:
        verbose_name = 'категория товаров'
        verbose_name_plural = 'категории товаров'

    caption = models.CharField(
        verbose_name='название',  unique=True, max_length=255)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.caption


class Good(models.Model):

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    caption = models.CharField(
        verbose_name='название', unique=True, max_length=255)
    brief_description = models.TextField(
        verbose_name='краткое описание', blank=True)
    full_description = models.TextField(
        verbose_name='полное описание', blank=True)
    image = models.ImageField(verbose_name='изображение', blank=True)
    category = models.ForeignKey(
        GoodsCategory, models.CASCADE, verbose_name='категория')

    def __str__(self):
        return self.caption
    
    def get_image_path(self):
        return str(self.image)

class GoodСharacteristic(models.Model):

    class Meta:
        verbose_name = 'характеристика товара'
        verbose_name_plural = 'характеристики товара'

    caption = models.CharField(
        verbose_name='название', max_length=255)
    value = models.TextField(verbose_name='значение', blank=True)
    good = models.ForeignKey(Good, models.CASCADE, verbose_name='товар')

    def __str__(self):
        return f'"{self.caption}" для "{self.good.caption}"'

django_basic/geekshop/mainapp/forms.py
from django.forms.models import ModelForm

from mainapp.models import Good


class GoodCreateForm(ModelForm):
    
    class Meta:
        model = Good
        fields = ("__all__",)

django_basic/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Good, GoodsCategory, GoodСharacteristic


def main(request):
    return render(request, 'mainapp/index.html')


def catalog(request):
    data = dict()
    for cat in GoodsCategory.objects.all():
        goods = Good.objects.filter(category=cat)[:3]
        data[cat] = goods
    return render(request, 'mainapp/catalog.html', {'data': data, })


def category(request, category_id):
    cat = get_object_or_404(GoodsCategory, pk=category_id)
    return render(request, 'mainapp/category.html', {
        'category': cat, 
        'goods': Good.objects.filter(category=cat),
    })


def item(request, item_id):
    good = get_object_or_404(Good, pk=item_id)
    return render(request, 'mainapp/item.html', {
        'good': good,
        'characteristics': GoodСharacteristic.objects.filter(good=good), 
    })


def contacts(request):
    return render(request, 'mainapp/contacts.html')

django_basic/geekshop/mainapp/templates/mainapp/catalog.html
{% extends "base.html" %}
{% load static %}

{% block title %}Каталог | {% endblock title %}

{% block content %}
    <h1>Каталог товаров</h1>
    {% for cat, goods in data.items %}
        <h3><a href="{% url 'catalog:category' cat.id %}">Категория "{{ cat.caption }}"</a></h3>
        <div class="row">
            {% for g in goods %}
                <div class="card">
                    <div class="section img">
                        <img src="{% static g.get_image_path %}" alt="">
                    </div>
                    <div class="section title"><a href="{% url 'catalog:item' g.id %}">{{ g.caption }}</a></div>
                    <div class="section">{{ g.brief_description }}</div>
                </div>
            {% endfor %}
            <div class="clr"></div>
        </div>
    {% endfor %}
{% endblock content %}

django_basic/geekshop/mainapp/templates/mainapp/category.html
{% extends "base.html" %}
{% load static %}

{% block title %}Категория товаров | {% endblock title %}

{% block content %}
    <a href="{% url 'catalog:index' %}">К каталогу</a>
    <h1>Категория товара "{{ category.caption }}"</h1>
    <div class="row">
    {% for g in goods %}
        <div class="card">
            <div class="section img">
                <img src="{% static g.get_image_path %}" alt="">
            </div>
            <div class="section title"><a href="{% url 'catalog:item' g.id %}">{{ g.caption }}</a></div>
            <div class="section">{{ g.brief_description }}</div>
        </div>
    {% endfor %}
        <div class="clr"></div>
    </div>
{% endblock content %}

django_basic/geekshop/mainapp/templates/mainapp/contacts.html
{% extends "base.html" %}

{% block title %}Контакты | {% endblock title %}

{% block content %}
        <h1>Контакты</h1>

        <h3>Обратная связь</h3>
        <form action="#">
            <p><label for="name">Имя</label> <input type="text" id="name"></p>
            <p><label for="family">Фамилия</label> <input type="text" id="family"></p>
            <p><label for="phone">Контактный номер телефона</label> <input type="text" id="phone" placeholder="+7 ХХХ ХХХ-ХХ-ХХ"></p>
            <p><label for="phone">Контактный e-mail</label> <input type="text" id="email" placeholder="email@example.com"></p>
            <p><label for="message">Сообщение</label><br><textarea name="message" id="message" cols="50" rows="10" placeholder="Введите здесь текст своего сообщения"></textarea></p>
            <p>Вам понравился наш магазин?<br>
                <input type="radio" name="group" id="yes" checked><label for="yes">Да</label>
                <input type="radio" name="group" id="no"><label for="no">Нет</label>
                <input type="radio" name="group" id="hz"><label for="hz">Не знаю</label>
            </p>
            <input type="submit"> <input type="reset" value="Очистить">
        </form>

        <h3>Как нас найти</h3>
        <h4>Адрес</h4>
        <p>Россия, Москва, Красная площадь, 1</p>
        <h4>Карта</h4>
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Acad73d3109678908402c24d5f2d32ce54dcafc4ebc1f5dc38f51ed6fb1c069e7&amp;width=840&amp;height=374&amp;lang=ru_RU&amp;scroll=true" class="map"></script>
{% endblock content %}

django_basic/geekshop/mainapp/templates/mainapp/index.html
{% extends "base.html" %}

{% block content %}
        <h1>Магазин компьютерных комплектующих &#171;Кнопка&#187;</h1>
        <h3>Мы приветствуем наших покупателей</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto eligendi provident delectus, expedita totam vero ea autem id a at vel cum, tempore suscipit magni commodi, saepe adipisci. Assumenda consequuntur eaque aspernatur est ex velit odit distinctio libero magni deserunt.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa voluptatem recusandae quos nisi sed necessitatibus alias reiciendis quod rem consectetur blanditiis, nam assumenda. Harum alias commodi officia maxime quod illo iusto suscipit inventore, dolores voluptates? Modi, possimus, nobis! Corporis, voluptate?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, ducimus id, repellendus quos blanditiis laboriosam facilis earum. Ullam debitis obcaecati vitae voluptas rem adipisci, consectetur assumenda quae mollitia, et repudiandae. Ullam consequuntur necessitatibus corporis harum soluta nulla eum! Nemo, minima.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam cumque accusamus neque maxime veritatis, velit iure! Id distinctio hic perferendis laudantium temporibus libero quibusdam quod doloribus neque quisquam maxime perspiciatis laboriosam sapiente iste veniam, rem maiores ipsa ullam aspernatur totam.</p>
{% endblock content %}

django_basic/geekshop/mainapp/templates/mainapp/item.html
{% extends "base.html" %}
{% load static %}

{% block title %}Товар "{{ good.caption|title }}" |{% endblock title %}

{% block content %}
    <a href="{% url 'catalog:category' good.category.id%}">К категории</a> | <a href="{% url 'catalog:index' %}">К каталогу</a>

    <h1>{{ good.caption|title }}</h1>
    <h3>Описание товара</h3>
    <a href="{% static good.get_image_path %}" target="_blank"><img src="{% static good.get_image_path %}" alt="{{ good.caption|title }}" width="200" class="goodprev"></a>
    <p class="brief description">{{ good.brief_description }}</p>
    <button class="buy">Купить</button>
    <div class="clr"></div>
    <h3>Подробное описание товара</h3>
    <p class="full description">{{ good.full_description|linebreaks }}</p>

    <h3>Характеристики товара</h3>
    <ul class="characteristics">
    {% for ch in characteristics %}
        <li><span><b>{{ ch.caption }} </b></span>{{ ch.value }}</li>
    {% endfor %}
    </ul>
{% endblock content %}