django_basic/geekshop/adminapp/urls.py
from django.urls import include, path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.home, name='home'),

    path('users/create/', adminapp.ShopUserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.ShopUserList.as_view(), name='users'),
    path("users/update/<int:pk>/", adminapp.ShopUserUpdateView.as_view(), name="user_update"),
    path("users/delete/<int:pk>/", adminapp.ShopUserDeleteView.as_view(), name="user_delete"),

    path('categories/create/', adminapp.GoodsCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.GoodsCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/',
         adminapp.GoodsCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/',
         adminapp.GoodsCategoryDeleteView.as_view(), name='category_delete'),

    path('goods/create/', adminapp.GoodCreateView.as_view(), name='good_create'),
    path('goods/read/category/<int:pk>/', adminapp.goods, name='goods'),
    path('goods/read/<int:pk>/', adminapp.GoodDetailView.as_view(), name='good_read'),
    path('goods/update/<int:pk>/', adminapp.GoodUpdateView.as_view(), name='good_update'),
    path('goods/delete/<int:pk>/', adminapp.GoodDeleteView.as_view(), name='good_delete'),
]

django_basic/geekshop/authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'), 
    path('logout/', authapp.logout, name='logout'), 
    path('user/<slug:username>', authapp.userinfo, name='userinfo'), 
    path('user/register/', authapp.reg, name='reg'), 
    path('user/edit/<slug:username>', authapp.useredit, name='useredit'), 
#    path('user/')
]

django_basic/geekshop/basketapp/urls.py
from basketapp import views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

django_basic/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')), 
    path('admin/', include('adminapp.urls', namespace='admin')),
]

django_basic/geekshop/mainapp/urls.py
from django.urls import path
from .views import catalog, item, category

app_name = 'mainapp'

urlpatterns = [
    path('', catalog, name="index"), 
    path('category/<int:category_id>', category, name="category"), 
    path('item/<int:item_id>', item, name="item"), 
]

django_basic/geekshop/mainapp/models.py
from django.db import models


class GoodCharTemple(models.Model):

    class Meta:
        verbose_name = 'образец характеристики товара'
        verbose_name_plural = 'образцы характеристик товара'

    caption = models.CharField(verbose_name='название', max_length=255)
    category = models.ForeignKey(
        'GoodsCategory', models.CASCADE, verbose_name='категория')
    
    def __str__(self):
        return f'"{self.caption}" для "{self.category.caption}"'


class GoodsCategory(models.Model):

    class Meta:
        verbose_name = 'категория товаров'
        verbose_name_plural = 'категории товаров'

    caption = models.CharField(
        verbose_name='название',  unique=True, max_length=255)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.caption


class Good(models.Model):

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    caption = models.CharField(
        verbose_name='название', unique=True, max_length=255)
    brief_description = models.TextField(
        verbose_name='краткое описание', blank=True)
    full_description = models.TextField(
        verbose_name='полное описание', blank=True)
    image = models.ImageField(verbose_name='изображение', blank=True)
    category = models.ForeignKey(
        GoodsCategory, models.CASCADE, verbose_name='категория')

    def __str__(self):
        return self.caption
    
    def get_image_path(self):
        return str(self.image)

class GoodСharacteristic(models.Model):

    class Meta:
        verbose_name = 'характеристика товара'
        verbose_name_plural = 'характеристики товара'

    caption = models.CharField(
        verbose_name='название', max_length=255)
    value = models.TextField(verbose_name='значение', blank=True)
    good = models.ForeignKey(Good, models.CASCADE, verbose_name='товар')

    def __str__(self):
        return f'"{self.caption}" для "{self.good.caption}"'

django_basic/geekshop/mainapp/forms.py
from django.forms.models import ModelForm

from mainapp.models import Good


class GoodCreateForm(ModelForm):
    
    class Meta:
        model = Good
        fields = ("__all__",)

django_basic/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Good, GoodsCategory, GoodСharacteristic


def main(request):
    return render(request, 'mainapp/index.html')


def catalog(request):
    data = dict()
    for cat in GoodsCategory.objects.all():
        goods = Good.objects.filter(category=cat)[:3]
        data[cat] = goods
    return render(request, 'mainapp/catalog.html', {'data': data, })


def category(request, category_id):
    cat = get_object_or_404(GoodsCategory, pk=category_id)
    return render(request, 'mainapp/category.html', {
        'category': cat, 
        'goods': Good.objects.filter(category=cat),
    })


def item(request, item_id):
    good = get_object_or_404(Good, pk=item_id)
    return render(request, 'mainapp/item.html', {
        'good': good,
        'characteristics': GoodСharacteristic.objects.filter(good=good), 
    })


def contacts(request):
    return render(request, 'mainapp/contacts.html')

django_basic/geekshop/mainapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}Магазин компьютерных комплектующих &#171;Кнопка&#187;</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css">
    {% block css %}{% endblock css %}
</head>

<body>
    <header class="row">
        <div class="col-sm">
            <img id="logo" src="{% static 'img/logo_h75px.png' %}" alt="">
        </div>
        <div class="col-sm user">
            {% if user.is_authenticated %}
            <div class="row">
                {% if user.avatar_path %}<div class="col-sm-5"><img src="{% static user.avatar_path %}" alt=""></div>{% endif %}
                <div class="col-sm">
                    <p><a href="{% url 'auth:userinfo' user.username %}">{{ user.username }}</a></p>
                    <p><a href="{% url 'auth:logout' %}">Выйти</a></p>
                </div>
            </div>
            {% else %}
            <a href="{% url 'auth:reg' %}">Регистрация</a> | 
            <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </div>
    </header>

    <div class="container">
        <div class="row">
            <nav class="col-sm-2">{% include 'menu.html' %}</nav>
            <div class="main col-sm">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
    <footer>
        {% block footer %}
        <small>Все права защищены &#169; 2019</small>
        {% endblock footer %}
    </footer>
</body>

</html>

django_basic/geekshop/mainapp/templates/menu.html
{% if user.is_authenticated and user.is_superuser %}
<a href="{% url 'adminapp:home' %}">Админка</a>
{% endif %}
<a href="{% url 'main' %}">Главная</a>
<a href="{% url 'catalog:index' %}">Каталог</a>
<a href="{% url 'contacts' %}">Контакты</a>
<a href="{% url 'basket:view' %}" class="basket">Карзина{% if basket %} <span>({{ basket.0.get_all_total_quantity }}
        товаров на сумму {{ basket.0.get_all_total_price }})</span>{% endif %}</a>